import { redirect } from "next/navigation";
import Link from "next/link";
import { LockKeyhole, Mail } from "lucide-react";
import { loginWithPassword, requestMagicLink } from "@/app/admin/actions";
import { getAdminUser } from "@/lib/admin-auth";

export default async function AdminLogin({ searchParams }: { searchParams: Promise<{ sent?: string; error?: string }> }) {
  if (await getAdminUser()) redirect("/admin");
  const query = await searchParams;
  const input = "mt-1.5 w-full rounded-xl border border-black/10 bg-white px-4 py-3 outline-none focus:border-[var(--clay)]";
  return <main className="flex min-h-screen items-center justify-center bg-[#f5f0e8] px-4 py-8"><section className="w-full max-w-md rounded-3xl border border-black/10 bg-[#fbf8f2] p-6 shadow-sm sm:p-10"><p className="eyebrow">Katey Coaching</p><h1 className="mt-3 font-display text-4xl text-[var(--plum)]">Admin login</h1><p className="mt-4 text-sm text-foreground/65">Enter your approved email address. We will send you a secure, one-time login link.</p>{query.sent && <p className="mt-5 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900">Login link sent. Please check your inbox and open only the newest message.</p>}{query.error === "credentials" && <p className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-900">The email address or password is incorrect. You can still use the secure login link above.</p>}{query.error === "unauthorized" && <p className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-900">This email address is not approved for Admin access.</p>}{query.error === "expired" && <p className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-900">This link has expired. Please request a new one.</p>}<form action={requestMagicLink} className="mt-6 space-y-4"><label className="block text-sm font-medium">Email<input name="email" type="email" required autoComplete="email" className={input} /></label><button className="flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-[var(--plum)] px-4 py-3 text-sm font-medium text-white"><Mail className="size-4" />Send secure login link</button></form><details className="mt-5 border-t border-black/10 pt-5"><summary className="cursor-pointer text-center text-sm text-foreground/55">Sign in with a password instead</summary><form action={loginWithPassword} className="mt-4 space-y-3"><label className="block text-sm font-medium">Email<input name="email" type="email" required autoComplete="username" className={input} /></label><label className="block text-sm font-medium">Password<input name="password" type="password" required autoComplete="current-password" className={input} /></label><div className="text-right"><Link href="/admin/forgot-password" className="text-sm font-medium text-[var(--plum)] underline">Forgot password?</Link></div><button className="flex min-h-11 w-full items-center justify-center gap-2 rounded-xl border border-black/10 bg-white px-4 py-3 text-sm text-[var(--plum)]"><LockKeyhole className="size-4" />Sign in with password</button></form></details><Link href="/en" className="mt-6 block text-center text-xs text-foreground/50">Back to website</Link></section></main>;
}
