export type AdminTutorial = {
  id: string;
  title: string;
  description: string;
  category: string;
  steps: readonly string[];
  result: string;
};

export const ADMIN_TUTORIALS: readonly AdminTutorial[] = [
  { id: "overview", title: "Admin dashboard overview", description: "Find the right place for each change.", category: "Getting started", steps: ["Choose Website Content for the homepage, About, Mission or Contact page.", "Choose Programs or Recipes to edit an existing item or add a new draft.", "Choose Media to review uploaded images. Use Help & Tutorials from any Admin page when you are unsure."], result: "Your changes only reach visitors after you select Save & publish." },
  { id: "edit-text", title: "How to change website text", description: "Update words without changing the website design.", category: "Website Content", steps: ["Open Website Content and expand the page you want.", "Open English, German or Slovak and change the relevant field.", "Select Preview page to check it, then return to Admin and select Save & publish."], result: "The saved wording appears in the language section you edited." },
  { id: "languages", title: "Editing the three languages", description: "Understand which changes are shared and which need a translation.", category: "Getting started", steps: ["Change shared details such as an image, price, order or Published status only once. They apply to all languages.", "For wording, open English, German or Slovak. Each box contains the words visitors see in that language.", "If you only have English text, leave the other translation empty instead of guessing. Programs safely use English until a real translation is added.", "Save once after checking every language you changed."], result: "The site keeps real translations separate while shared changes update everywhere automatically." },
  { id: "replace-image", title: "How to replace an image", description: "Choose and check a new website image safely.", category: "Media", steps: ["Open the page, program or recipe and select Replace image.", "Choose a JPG, PNG, WebP or AVIF file smaller than 10 MB.", "Check the new preview, then select Upload image.", "Wait for the success message and save the whole form."], result: "The image changes only after both the upload and the form save succeed." },
  { id: "edit-about", title: "How to update your About page", description: "Edit your biography, personal opening, headings and main portrait.", category: "Website Content", steps: ["Open Website Content and expand About Katey — main section.", "Replace the portrait if needed, then open the language you want to edit.", "Use a blank line between biography paragraphs. You do not need special formatting.", "Open About Katey — personal opening if you want to change the short statement beside the portrait.", "Preview the page and select Save & publish."], result: "Your About heading, biography, personal opening and portrait are updated." },
  { id: "edit-mission", title: "How to update your Mission", description: "Change the Mission words while keeping its design.", category: "Website Content", steps: ["Open Website Content and expand My Mission.", "Open the language you want and replace the heading or Mission text.", "Replace the image only if you want a different Mission photograph.", "Preview, then select Save & publish."], result: "The Mission layout stays protected; only your chosen content changes." },
  { id: "edit-program", title: "How to edit your coaching program", description: "Change the real program details, lists, price or image.", category: "Programs", steps: ["Open Programs and select the program name.", "Change shared details such as price and image once.", "Open a language to edit its title, audience list, included items, duration or button label.", "Use Add item or the delete icon to manage list entries, then preview and publish."], result: "The published program page uses the saved information." },
  { id: "add-program", title: "How to add a new program", description: "Prepare a genuine future offer without showing it too early.", category: "Programs", steps: ["Open Programs and select Add program.", "Add the English title, program details, price and a real image.", "Select Save draft. A draft is private and does not appear on the public website.", "Add the verified translations and select Save & publish only when the offer is ready."], result: "A draft stays private; a published program becomes available publicly." },
  { id: "add-recipe", title: "How to add a recipe", description: "Create a recipe with simple ingredient and instruction lists.", category: "Recipes", steps: ["Open Recipes and select Add recipe.", "Add the title, description, times, servings and photograph.", "Use Add ingredient and Add step. Use the delete icon to remove a row.", "Select Save draft while the recipe is unfinished, or Save & publish when it is approved."], result: "Only published recipes appear on the public Recipes page." },
  { id: "recipes-page", title: "How to edit the Recipes page", description: "Change the words around the public recipe list.", category: "Website Content", steps: ["Open Website Content and expand Recipes page introduction.", "Open the language you want to edit.", "Change the introduction, labels, quote or lower coaching section.", "Preview the Recipes page, then select Save & publish."], result: "The page wording changes without altering any individual recipe." },
  { id: "recipe-image", title: "How to change a recipe image", description: "Replace a food photograph and verify it before saving.", category: "Recipes", steps: ["Open Recipes and choose the recipe.", "Select Replace image and choose the new photograph.", "Check that the crop looks good in the preview, then select Upload image.", "Select Save draft or Save & publish at the bottom."], result: "The new image is connected to that recipe after the form is saved." },
  { id: "publishing", title: "Draft vs Published", description: "Choose whether visitors can see your work.", category: "Getting started", steps: ["Select Save draft when content is unfinished. Visitors cannot see a new draft.", "Use Preview where available to inspect your work.", "Select Save & publish only when the content and all required translations are ready."], result: "Draft means private work; Published means visible website content." },
  { id: "contact", title: "How to edit the Contact page", description: "Change the Contact heading, introduction, photograph or button wording.", category: "Website Content", steps: ["Open Website Content and expand Contact page.", "Open the required language and edit the words.", "Replace the main photograph if needed, preview the page and publish.", "The Name, Email and Message form remains protected and continues working normally."], result: "The page content changes without exposing email-delivery settings." },
  { id: "login", title: "How to access and leave Admin safely", description: "Sign in securely and close Admin when finished.", category: "Getting started", steps: ["Open the private /admin address and sign in with an approved account.", "Do not forward login emails or share the password.", "When finished, select Log out in the top-right corner—especially on a shared device."], result: "Logging out closes the private editing session." },
];
