export type AdminTutorial = { id: string; title: string; description: string; videoSrc: string; thumbnail: string; duration: string; category: string; steps: readonly string[] };

export const ADMIN_TUTORIALS: readonly AdminTutorial[] = [
  { id: "overview", title: "Admin dashboard overview", description: "Find every content area and understand the safe editing workflow.", videoSrc: "/tutorials/admin-overview.mp4", thumbnail: "/tutorials/admin-overview.jpg", duration: "2 min", category: "Getting started", steps: ["Open a dashboard card", "Choose the content you want to edit", "Preview and save your changes"] },
  { id: "edit-text", title: "How to change website text", description: "Update a heading or paragraph without touching the website design.", videoSrc: "/tutorials/edit-text.mp4", thumbnail: "/tutorials/edit-text.jpg", duration: "1 min", category: "Website Content", steps: ["Open Website Content", "Choose the page and language", "Edit, preview, then publish"] },
  { id: "replace-image", title: "How to replace an image", description: "Choose, preview and save a new website image safely.", videoSrc: "/tutorials/replace-image.mp4", thumbnail: "/tutorials/replace-image.jpg", duration: "1 min", category: "Media", steps: ["Select Replace image", "Check the preview", "Save the page or item"] },
  { id: "edit-about", title: "How to update your About page", description: "Edit your biography, headings and main portrait.", videoSrc: "/tutorials/edit-about.mp4", thumbnail: "/tutorials/edit-about.jpg", duration: "2 min", category: "Website Content", steps: ["Open Website Content", "Expand About page", "Update each language and publish"] },
  { id: "edit-mission", title: "How to update your Mission", description: "Replace the Mission wording while keeping its approved design.", videoSrc: "/tutorials/edit-mission.mp4", thumbnail: "/tutorials/edit-mission.jpg", duration: "1 min", category: "Website Content", steps: ["Open Website Content", "Expand My Mission", "Paste plain text, preview and publish"] },
  { id: "edit-program", title: "How to edit your coaching program", description: "Change program details, lists, price and image.", videoSrc: "/tutorials/edit-program.mp4", thumbnail: "/tutorials/edit-program.jpg", duration: "2 min", category: "Programs", steps: ["Open Programs and select a program", "Edit details or list items", "Preview and publish"] },
  { id: "add-program", title: "How to add a new program", description: "Create a draft for a genuine future coaching program.", videoSrc: "/tutorials/add-program.mp4", thumbnail: "/tutorials/add-program.jpg", duration: "2 min", category: "Programs", steps: ["Select Add program", "Complete English and add the image", "Save as draft until ready"] },
  { id: "add-recipe", title: "How to add a recipe", description: "Create a recipe draft with ingredients and numbered steps.", videoSrc: "/tutorials/add-recipe.mp4", thumbnail: "/tutorials/add-recipe.jpg", duration: "3 min", category: "Recipes", steps: ["Select Add recipe", "Add details, ingredients and steps", "Save as draft or publish"] },
  { id: "recipe-image", title: "How to change a recipe image", description: "Replace a recipe photograph and verify its preview.", videoSrc: "/tutorials/recipe-image.mp4", thumbnail: "/tutorials/recipe-image.jpg", duration: "1 min", category: "Recipes", steps: ["Open the recipe", "Choose Replace image", "Check the preview and save"] },
  { id: "publishing", title: "Draft vs Published", description: "Know when changes are private and when visitors can see them.", videoSrc: "/tutorials/draft-vs-published.mp4", thumbnail: "/tutorials/draft-vs-published.jpg", duration: "1 min", category: "Getting started", steps: ["Use Save draft to keep work private", "Preview your content", "Use Save & publish when it is ready"] },
  { id: "contact", title: "How to edit the Contact page", description: "Change the Contact heading, introduction, image and button wording.", videoSrc: "/tutorials/edit-contact.mp4", thumbnail: "/tutorials/edit-contact.jpg", duration: "1 min", category: "Website Content", steps: ["Open Website Content", "Expand Contact page", "Preview and publish"] },
  { id: "login", title: "How to access and leave Admin safely", description: "Sign in securely and log out when you finish.", videoSrc: "/tutorials/login-logout.mp4", thumbnail: "/tutorials/login-logout.jpg", duration: "1 min", category: "Getting started", steps: ["Open the private Admin address", "Sign in with your approved account", "Use Log out when finished"] },
];
