import type { Locale } from "@/i18n/routing";

type Section = { title: string; paragraphs?: string[]; items?: string[] };

const EN: Section[] = [
  { title: "1. Provider and scope", paragraphs: ["These Terms and Conditions apply to coaching services provided by Katarina Gröflin, Katey Coaching, Kammermattweg 18, CH-4107 Ettingen, Switzerland, katey.coaching.newlife@gmail.com. They apply to consumers and, where relevant, business clients. Mandatory rights under the law of a client's country of residence remain unaffected."] },
  { title: "2. Contract formation", paragraphs: ["Program information on the website is an invitation to enquire, not a binding offer. After the free consultation, the client normally has three days to decide. If Katey accepts the client, the client then normally has three further days to complete payment through Stripe.", "A contract is formed when the client accepts these Terms using an unticked checkbox at Stripe Checkout and payment is confirmed, or when Katey expressly confirms the agreement in writing. The checkout summary and confirmation email form part of the contract."] },
  { title: "3. Services", items: ["The Full Transformation: a fixed 90-day personalised coaching program. The 90 days begin when the client receives the first workout video. It ends automatically and does not renew.", "Move and Grow: a monthly online training subscription with weekly check-ins. It renews monthly until cancelled, has no minimum term and can be cancelled through the Stripe customer portal for the next billing cycle.", "Find Your Way Through: a 60-minute one-to-one conversation paid in advance through Stripe at CHF 80 per session. It is faith-based coaching and is not medical treatment, psychotherapy, crisis care or a substitute for professional healthcare."], paragraphs: ["The description displayed for the selected program at checkout determines the agreed scope. Reasonable changes may be made where needed for safety or to adapt the service to the client's goals, health, equipment and progress."] },
  { title: "4. Prices and payment", items: ["The Full Transformation: CHF 1,290 paid in full; two monthly payments of CHF 700 (CHF 1,400 total); or three monthly payments of CHF 480 (CHF 1,440 total).", "Move and Grow: CHF 200 per monthly billing cycle.", "Find Your Way Through: CHF 80 per 60-minute session, paid in advance."], paragraphs: ["The total price and billing schedule are shown before payment. Payments are processed by Stripe. Instalments are charged automatically on their fixed monthly schedule, including during an illness pause. They are a payment schedule for the full fixed-term price, not separate monthly purchases. If a payment fails, coaching pauses until payment is successfully completed, subject to mandatory law."] },
  { title: "5. Appointments and illness pauses", paragraphs: ["Appointments may be cancelled or rescheduled with at least 24 hours' notice. A session cancelled later or missed without notice is forfeited without replacement or credit.", "If a client is genuinely ill or injured, informs Katey in advance and provides a doctor's confirmation, the affected program pauses and is extended by the missed days. This does not apply to avoidable scheduling conflicts such as being busy. An illness pause may last no more than 60 days.", "If the pause exceeds 60 days, the program closes. The client pays proportionally only for coaching up to the start of the pause. A client who paid in full receives a proportional refund for unused coaching days. For an instalment plan, future Stripe charges stop; any further reconciliation depends on the agreed proportional calculation and mandatory law."] },
  { title: "6. Cancellation, renewal and refunds", paragraphs: ["The Full Transformation ends after 90 days and does not renew. A client may stop participating at any time, but stopping early or changing their mind does not itself create a refund entitlement. The special proportional settlement for an illness pause exceeding 60 days remains unaffected.", "Move and Grow may be cancelled at any time through the Stripe customer portal. Cancellation takes effect at the end of the current paid billing cycle, prevents the next renewal and does not normally generate a partial-period refund.", "Find Your Way Through appointments are subject to the 24-hour rule above.", "No-refund provisions do not apply where mandatory law requires a refund, where Katey permanently cannot provide the agreed service, or where the client has statutory remedies for defective performance. Nothing in these Terms restricts rights that cannot lawfully be excluded."] },
  { title: "7. EU/EEA and other mandatory consumer rights", paragraphs: ["Consumers in the EU/EEA may have a 14-day right to withdraw from a distance service contract. Where the client asks for coaching to begin during that period, the client expressly requests immediate performance. If the client validly withdraws before the service is fully performed, Katey may charge the proportionate value of services already supplied where permitted by law. The withdrawal right is lost after full performance only where the legal requirements, including prior express consent and acknowledgement, are met.", "The Stripe Terms checkbox records acceptance of these Terms. Any separate consent required to begin performance during a withdrawal period must also be obtained expressly and must not be pre-selected."] },
  { title: "8. Clients under 18", paragraphs: ["A client under 18 may participate only with prior consent from a parent or legal guardian. The parent or guardian must confirm consent by email, complete the payment and support compliance with these Terms. Katey may request stronger proof or decline coaching where age, consent or safety cannot be verified. The suitability of email consent remains subject to legal review."] },
  { title: "9. Health and safety", items: ["Clients must give complete and accurate information about injuries, pain, illness, pregnancy, medication and any other matter relevant to safe participation.", "After the consultation, clients must confirm their health information and safety acknowledgement in writing.", "Where a health concern exists, medical approval is required before training begins or resumes.", "Clients must follow instructions, use suitable equipment and surroundings, work within their abilities, stop immediately if they experience pain, dizziness or unusual symptoms, and seek appropriate medical help."], paragraphs: ["Katey may pause, modify or refuse an activity where she reasonably considers it unsafe. The client remains responsible for obtaining appropriate health and accident insurance."] },
  { title: "10. No medical service or guaranteed result", paragraphs: ["Coaching, nutrition information and faith-based conversations are educational and supportive services. They do not diagnose, treat or cure disease and do not replace a doctor, registered dietitian, psychotherapist or emergency service. No specific physical, health, weight, financial, emotional or spiritual result is guaranteed. Results depend on many factors, including the client's participation and circumstances."] },
  { title: "11. Assumption of risk and liability", paragraphs: ["Physical activity involves inherent risks, including soreness, strains, falls and other injury. The client knowingly accepts the ordinary risks that remain despite reasonable instruction and care.", "Katey remains responsible for exercising the care required by applicable law. Liability is excluded or limited only to the extent legally permitted. Nothing excludes liability for intentional misconduct or gross negligence, or any liability that applicable law does not allow to be excluded. The client's acknowledgement of risk does not excuse unsafe or negligent coaching."] },
  { title: "12. Client cooperation and conduct", paragraphs: ["The client is responsible for providing timely information, attending agreed appointments, completing payments and using the program only for personal purposes. Harassment, abuse, unlawful conduct or conduct that creates a safety risk may lead to suspension or termination. Any financial consequences will be assessed fairly under the circumstances and mandatory law."] },
  { title: "13. Intellectual property", paragraphs: ["Training plans, videos, written materials and other program content remain the property of Katey or the relevant rights holder. The client receives a personal, non-transferable right to use them during and for the purpose of the program. They may not be shared, sold, published, copied commercially or used to coach others without written permission."] },
  { title: "14. Personal data and communications", paragraphs: ["Personal data is processed as described in the Privacy Notice. Written health information is deleted when the client's coaching ends, unless retention is required by mandatory law. Stripe processes payment data under its own privacy terms. Email and WhatsApp may be used for agreed coaching communication; they should not be used for emergencies. Clients should avoid sending unnecessary sensitive information through unsecured channels."] },
  { title: "15. Katey's holidays and unavailability", paragraphs: ["For a planned holiday, clients are informed in advance and the program is extended by the number of days Katey is away. For unplanned temporary unavailability, the program pauses and extends when Katey can resume. No substitute coach or refund is provided for a temporary pause. Mandatory rights remain unaffected if Katey is permanently unable to provide the remaining service."] },
  { title: "16. Governing law and disputes", paragraphs: ["Swiss law applies, excluding its conflict-of-law rules, to the extent this choice is permitted. Mandatory consumer protections and mandatory places of jurisdiction remain unaffected. The parties should first try to resolve concerns directly by email. Where no mandatory forum applies, the courts competent for Ettingen, Basel-Landschaft, Switzerland have jurisdiction."] },
  { title: "17. Contact and version", paragraphs: ["Questions, cancellations and legal notices may be sent to katey.coaching.newlife@gmail.com. The version accepted at checkout governs the contract. Material changes do not retroactively alter an existing fixed-term purchase without agreement."] },
];

const DE: Section[] = [
  { title: "1. Anbieterin und Geltungsbereich", paragraphs: ["Diese Allgemeinen Geschäftsbedingungen gelten für Coaching-Leistungen von Katarina Gröflin, Katey Coaching, Kammermattweg 18, CH-4107 Ettingen, Schweiz, katey.coaching.newlife@gmail.com. Sie gelten für Verbraucherinnen und Verbraucher sowie, soweit relevant, für Geschäftskunden. Zwingende Rechte nach dem Recht des Wohnsitzstaates der Kundin oder des Kunden bleiben unberührt."] },
  { title: "2. Vertragsabschluss", paragraphs: ["Programminformationen auf der Website sind eine Einladung zur Kontaktaufnahme und kein verbindliches Angebot. Nach der kostenlosen Beratung hat die Kundin oder der Kunde normalerweise drei Tage Zeit für die Entscheidung. Nimmt Katey die Person an, stehen danach normalerweise weitere drei Tage für die Zahlung über Stripe zur Verfügung.", "Der Vertrag kommt zustande, wenn die AGB über eine nicht vorangekreuzte Checkbox im Stripe-Checkout akzeptiert und die Zahlung bestätigt wird oder Katey die Vereinbarung ausdrücklich schriftlich bestätigt. Checkout-Zusammenfassung und Bestätigungs-E-Mail sind Bestandteil des Vertrags."] },
  { title: "3. Leistungen", items: ["The Full Transformation: personalisiertes Coaching mit fester Laufzeit von 90 Tagen. Die 90 Tage beginnen, wenn die Kundin oder der Kunde das erste Trainingsvideo erhält. Das Programm endet automatisch und verlängert sich nicht.", "Move and Grow: monatliches Online-Trainingsabonnement mit wöchentlichen Check-ins. Es verlängert sich monatlich bis zur Kündigung, hat keine Mindestlaufzeit und kann über das Stripe-Kundenportal zum nächsten Abrechnungszeitraum gekündigt werden.", "Find Your Way Through: 60-minütiges Einzelgespräch, das vorab über Stripe mit CHF 80 pro Termin bezahlt wird. Es ist glaubensbasiertes Coaching und keine medizinische Behandlung, Psychotherapie, Krisenhilfe oder Ersatz für professionelle Gesundheitsversorgung."], paragraphs: ["Die beim Checkout angezeigte Beschreibung des ausgewählten Programms bestimmt den vereinbarten Umfang. Angemessene Änderungen sind möglich, wenn sie für die Sicherheit oder die Anpassung an Ziele, Gesundheit, Ausrüstung und Fortschritt erforderlich sind."] },
  { title: "4. Preise und Zahlung", items: ["The Full Transformation: CHF 1.290 bei vollständiger Vorauszahlung; zwei monatliche Zahlungen à CHF 700 (insgesamt CHF 1.400); oder drei monatliche Zahlungen à CHF 480 (insgesamt CHF 1.440).", "Move and Grow: CHF 200 pro monatlichem Abrechnungszeitraum.", "Find Your Way Through: CHF 80 pro 60-minütigem Termin, im Voraus bezahlt."], paragraphs: ["Gesamtpreis und Zahlungsplan werden vor der Zahlung angezeigt. Zahlungen werden über Stripe verarbeitet. Raten werden auch während einer Krankheitspause automatisch nach dem festen monatlichen Zeitplan eingezogen. Sie sind ein Zahlungsplan für den vollständigen Festpreis und keine einzelnen Monatskäufe. Schlägt eine Zahlung fehl, pausiert das Coaching bis zur erfolgreichen Zahlung, vorbehaltlich zwingenden Rechts."] },
  { title: "5. Termine und Krankheitspausen", paragraphs: ["Termine können mit mindestens 24 Stunden Vorlauf abgesagt oder verschoben werden. Bei späterer Absage oder Nichterscheinen ohne Mitteilung verfällt der Termin ohne Ersatz oder Gutschrift.", "Ist eine Person tatsächlich krank oder verletzt, informiert Katey im Voraus und legt eine ärztliche Bestätigung vor, pausiert das Programm und verlängert sich um die ausgefallenen Tage. Dies gilt nicht für vermeidbare Terminkonflikte wie Zeitmangel. Eine Krankheitspause darf höchstens 60 Tage dauern.", "Überschreitet die Pause 60 Tage, wird das Programm beendet. Bezahlt wird anteilig nur das Coaching bis zum Beginn der Pause. Bei vollständiger Vorauszahlung wird der ungenutzte Anteil erstattet. Bei Ratenzahlung werden zukünftige Stripe-Abbuchungen gestoppt; eine weitere Abrechnung richtet sich nach der bestätigten anteiligen Berechnung und zwingendem Recht."] },
  { title: "6. Kündigung, Verlängerung und Rückerstattungen", paragraphs: ["The Full Transformation endet nach 90 Tagen ohne Verlängerung. Die Teilnahme kann jederzeit beendet werden; ein vorzeitiger Ausstieg oder Meinungswechsel begründet für sich allein keinen Erstattungsanspruch. Die besondere anteilige Abrechnung bei einer Krankheitspause von mehr als 60 Tagen bleibt unberührt.", "Move and Grow kann jederzeit über das Stripe-Kundenportal gekündigt werden. Die Kündigung wirkt zum Ende des bezahlten Abrechnungszeitraums, verhindert die nächste Verlängerung und führt normalerweise nicht zu einer anteiligen Erstattung.", "Für Find Your Way Through gilt die vorstehende 24-Stunden-Regel.", "Der Ausschluss von Rückerstattungen gilt nicht, soweit zwingendes Recht eine Erstattung verlangt, Katey die verbleibende Leistung dauerhaft nicht erbringen kann oder gesetzliche Ansprüche wegen mangelhafter Leistung bestehen. Unabdingbare Rechte werden nicht eingeschränkt."] },
  { title: "7. EU-/EWR- und andere zwingende Verbraucherrechte", paragraphs: ["Verbraucherinnen und Verbraucher in der EU oder im EWR können bei Fernabsatzverträgen über Dienstleistungen ein 14-tägiges Widerrufsrecht haben. Soll das Coaching in dieser Zeit beginnen, verlangt die Person ausdrücklich den sofortigen Leistungsbeginn. Bei wirksamem Widerruf vor vollständiger Leistung kann Katey den gesetzlich zulässigen anteiligen Wert bereits erbrachter Leistungen berechnen. Das Widerrufsrecht erlischt nach vollständiger Leistung nur, wenn alle gesetzlichen Voraussetzungen einschließlich vorheriger ausdrücklicher Zustimmung und Kenntnisnahme erfüllt sind.", "Die Stripe-Checkbox dokumentiert die Annahme dieser AGB. Jede zusätzlich erforderliche Zustimmung zum Leistungsbeginn während einer Widerrufsfrist muss ebenfalls ausdrücklich und ohne Vorauswahl erfolgen."] },
  { title: "8. Minderjährige", paragraphs: ["Personen unter 18 Jahren dürfen nur mit vorheriger Zustimmung eines Elternteils oder einer gesetzlichen Vertretung teilnehmen. Diese Person bestätigt die Zustimmung per E-Mail, führt die Zahlung aus und unterstützt die Einhaltung dieser AGB. Katey kann einen stärkeren Nachweis verlangen oder das Coaching ablehnen, wenn Alter, Zustimmung oder Sicherheit nicht verifiziert werden können. Ob die Zustimmung per E-Mail ausreicht, bleibt Gegenstand der rechtlichen Prüfung."] },
  { title: "9. Gesundheit und Sicherheit", items: ["Kundinnen und Kunden informieren vollständig und wahrheitsgemäss über Verletzungen, Schmerzen, Krankheiten, Schwangerschaft, Medikamente und alle weiteren sicherheitsrelevanten Umstände.", "Nach der Beratung werden Gesundheitsangaben und Sicherheitshinweise schriftlich bestätigt.", "Bei gesundheitlichen Bedenken ist vor Beginn oder Wiederaufnahme des Trainings eine ärztliche Freigabe erforderlich.", "Anweisungen sind zu befolgen, geeignete Ausrüstung und Umgebung zu verwenden, die eigenen Grenzen einzuhalten und bei Schmerzen, Schwindel oder ungewöhnlichen Symptomen sofort aufzuhören und medizinische Hilfe zu suchen."], paragraphs: ["Katey kann eine Aktivität pausieren, anpassen oder ablehnen, wenn sie diese vernünftigerweise für unsicher hält. Kundinnen und Kunden bleiben für geeigneten Kranken- und Unfallversicherungsschutz verantwortlich."] },
  { title: "10. Keine medizinische Leistung oder Erfolgsgarantie", paragraphs: ["Coaching, Ernährungsinformationen und glaubensbasierte Gespräche sind Bildungs- und Unterstützungsleistungen. Sie diagnostizieren, behandeln oder heilen keine Krankheit und ersetzen keine Ärztin, keinen Arzt, keine anerkannte Ernährungsfachperson, Psychotherapie oder Notfallhilfe. Bestimmte körperliche, gesundheitliche, gewichtsbezogene, finanzielle, emotionale oder geistliche Ergebnisse werden nicht garantiert."] },
  { title: "11. Risikoübernahme und Haftung", paragraphs: ["Körperliche Aktivität birgt unvermeidbare Risiken wie Muskelkater, Zerrungen, Stürze und andere Verletzungen. Die Kundin oder der Kunde akzeptiert bewusst die gewöhnlichen Risiken, die trotz angemessener Anleitung und Sorgfalt verbleiben.", "Katey bleibt zur gesetzlich erforderlichen Sorgfalt verpflichtet. Die Haftung wird nur im gesetzlich zulässigen Umfang ausgeschlossen oder begrenzt. Haftung für Vorsatz, grobe Fahrlässigkeit oder andere gesetzlich nicht ausschliessbare Fälle bleibt bestehen. Die Risikoanerkennung entschuldigt kein unsicheres oder fahrlässiges Coaching."] },
  { title: "12. Mitwirkung und Verhalten", paragraphs: ["Kundinnen und Kunden stellen Informationen rechtzeitig bereit, nehmen vereinbarte Termine wahr, leisten Zahlungen und verwenden das Programm nur persönlich. Belästigung, Missbrauch, rechtswidriges Verhalten oder Sicherheitsgefährdung kann zur Aussetzung oder Beendigung führen. Finanzielle Folgen werden nach den Umständen und zwingendem Recht angemessen beurteilt."] },
  { title: "13. Geistiges Eigentum", paragraphs: ["Trainingspläne, Videos, Texte und weitere Programminhalte bleiben Eigentum von Katey oder der jeweiligen Rechteinhaber. Es wird ein persönliches, nicht übertragbares Nutzungsrecht für den Programmzweck gewährt. Ohne schriftliche Erlaubnis dürfen Inhalte nicht geteilt, verkauft, veröffentlicht, kommerziell kopiert oder zum Coaching anderer verwendet werden."] },
  { title: "14. Personendaten und Kommunikation", paragraphs: ["Personendaten werden gemäss Datenschutzerklärung bearbeitet. Schriftliche Gesundheitsangaben werden nach Ende des Coachings gelöscht, sofern keine zwingende gesetzliche Aufbewahrungspflicht besteht. Stripe verarbeitet Zahlungsdaten nach eigenen Datenschutzbestimmungen. E-Mail und WhatsApp dürfen für vereinbarte Coaching-Kommunikation genutzt werden, jedoch nicht für Notfälle. Über ungesicherte Kanäle sollten keine unnötigen sensiblen Informationen versendet werden."] },
  { title: "15. Ferien und Abwesenheit von Katey", paragraphs: ["Bei geplanten Ferien werden die Kundinnen und Kunden im Voraus informiert und das Programm um Kateys Abwesenheitstage verlängert. Bei ungeplanter vorübergehender Abwesenheit pausiert das Programm und verlängert sich, sobald Katey fortfahren kann. Für eine vorübergehende Pause gibt es weder Ersatzcoach noch Rückerstattung. Kann Katey die restliche Leistung dauerhaft nicht erbringen, bleiben zwingende Rechte unberührt."] },
  { title: "16. Anwendbares Recht und Streitigkeiten", paragraphs: ["Soweit zulässig gilt Schweizer Recht unter Ausschluss seiner Kollisionsnormen. Zwingende Verbraucherschutzbestimmungen und zwingende Gerichtsstände bleiben unberührt. Anliegen sollen zunächst per E-Mail geklärt werden. Soweit kein zwingender Gerichtsstand gilt, sind die zuständigen Gerichte für Ettingen, Basel-Landschaft, Schweiz zuständig."] },
  { title: "17. Kontakt und Version", paragraphs: ["Fragen, Kündigungen und rechtliche Mitteilungen können an katey.coaching.newlife@gmail.com gesendet werden. Massgebend ist die beim Checkout akzeptierte Fassung. Wesentliche Änderungen verändern einen bestehenden Festzeitvertrag nicht rückwirkend ohne Zustimmung."] },
];

const SK: Section[] = [
  { title: "1. Poskytovateľka a rozsah pôsobnosti", paragraphs: ["Tieto obchodné podmienky sa vzťahujú na koučovacie služby poskytované Katarinou Gröflin, Katey Coaching, Kammermattweg 18, CH-4107 Ettingen, Švajčiarsko, katey.coaching.newlife@gmail.com. Vzťahujú sa na spotrebiteľov a podľa okolností aj na firemných klientov. Povinné práva podľa práva krajiny bydliska klienta zostávajú nedotknuté."] },
  { title: "2. Uzatvorenie zmluvy", paragraphs: ["Informácie o programoch na stránke sú výzvou na kontaktovanie, nie záväznou ponukou. Po bezplatnej konzultácii má klient spravidla tri dni na rozhodnutie. Ak Katey klienta prijme, klient má spravidla ďalšie tri dni na uskutočnenie platby cez Stripe.", "Zmluva vzniká, keď klient prijme tieto podmienky pomocou vopred nezaškrtnutého políčka v Stripe Checkout a platba je potvrdená, alebo keď Katey dohodu výslovne písomne potvrdí. Súhrn objednávky a potvrdzujúci e-mail sú súčasťou zmluvy."] },
  { title: "3. Služby", items: ["The Full Transformation: personalizovaný koučovací program na pevných 90 dní. Týchto 90 dní začína dňom, keď klient dostane prvé tréningové video. Program sa skončí automaticky a neobnovuje sa.", "Move and Grow: mesačné online tréningové predplatné s týždennými kontrolami; obnovuje sa každý mesiac až do zrušenia, nemá minimálnu dobu trvania a možno ho zrušiť cez zákaznícky portál Stripe pre ďalší fakturačný cyklus.", "Find Your Way Through: 60-minútový individuálny rozhovor, zaplatený vopred cez Stripe za 80 CHF za stretnutie. Ide o koučing založený na viere, nie o zdravotnú starostlivosť, psychoterapiu, krízovú pomoc ani náhradu odbornej liečby."], paragraphs: ["Rozsah dohody určuje opis vybraného programu zobrazený pri platbe. Primerané úpravy sú možné, ak sú potrebné pre bezpečnosť alebo prispôsobenie cieľom, zdraviu, vybaveniu a pokroku klienta."] },
  { title: "4. Ceny a platba", items: ["The Full Transformation: 1 290 CHF pri platbe vopred; dve mesačné platby po 700 CHF (spolu 1 400 CHF); alebo tri mesačné platby po 480 CHF (spolu 1 440 CHF).", "Move and Grow: 200 CHF za každý mesačný fakturačný cyklus.", "Find Your Way Through: 80 CHF za 60-minútové stretnutie, zaplatené vopred."], paragraphs: ["Celková cena a harmonogram platieb sa zobrazia pred zaplatením. Platby spracúva Stripe. Splátky sa automaticky účtujú podľa pevného mesačného harmonogramu aj počas zdravotnej pauzy. Sú platobným kalendárom celej ceny programu, nie samostatnými mesačnými nákupmi. Ak platba zlyhá, koučing sa pozastaví až do úspešného zaplatenia; už splatné sumy zostávajú dlžné s výhradou povinného práva."] },
  { title: "5. Termíny a zdravotné pauzy", paragraphs: ["Termín možno zrušiť alebo presunúť najmenej 24 hodín vopred. Pri neskoršom zrušení alebo neúčasti bez oznámenia termín prepadá bez náhrady alebo kreditu.", "Ak je klient skutočne chorý alebo zranený, oznámi to Katey vopred a predloží potvrdenie od lekára, program sa pozastaví a predĺži o vynechané dni. Zdravotná pauza môže trvať najviac 60 dní.", "Ak pauza presiahne 60 dní, program sa uzavrie. Klient zaplatí pomernú časť len za koučing do začiatku pauzy. Pri platbe vopred sa vráti pomerná suma za nevyužité dni; pri splátkach sa zastavia budúce platby Stripe a ďalšie vyrovnanie sa riadi potvrdeným pomerným výpočtom a povinným právom."] },
  { title: "6. Zrušenie, obnovenie a vrátenie peňazí", paragraphs: ["The Full Transformation skončí po 90 dňoch a neobnovuje sa. Klient môže prestať kedykoľvek, ale predčasné ukončenie alebo zmena názoru samy osebe nezakladajú nárok na vrátenie peňazí. Osobitné pomerné vyrovnanie pri zdravotnej pauze dlhšej ako 60 dní zostáva zachované.", "Move and Grow možno kedykoľvek zrušiť cez zákaznícky portál Stripe. Zrušenie platí na konci zaplateného fakturačného obdobia, zabráni ďalšiemu obnoveniu a bežne nezakladá nárok na pomerné vrátenie ceny.", "Na Find Your Way Through sa vzťahuje uvedené 24-hodinové pravidlo.", "Vylúčenie vrátenia peňazí neplatí, ak vrátenie vyžaduje povinný zákon, Katey nemôže trvalo poskytnúť zostávajúcu službu alebo má klient zákonné nároky pre chybné plnenie. Práva, ktoré nemožno vylúčiť, zostávajú nedotknuté."] },
  { title: "7. Práva spotrebiteľov v EÚ/EHP a iné povinné práva", paragraphs: ["Spotrebitelia v EÚ alebo EHP môžu mať pri zmluve o službe uzatvorenej na diaľku 14-dňové právo na odstúpenie. Ak klient požiada o začatie koučingu počas tejto lehoty, výslovne žiada okamžité plnenie. Pri platnom odstúpení pred úplným poskytnutím služby môže Katey v zákonom povolenom rozsahu účtovať pomernú hodnotu už poskytnutých služieb. Právo zanikne po úplnom plnení iba pri splnení zákonných podmienok vrátane predchádzajúceho výslovného súhlasu a potvrdenia klienta.", "Zaškrtnutie políčka Stripe zaznamenáva prijatie týchto podmienok. Každý samostatne požadovaný súhlas so začatím služby počas lehoty na odstúpenie musí byť tiež výslovný a nesmie byť vopred označený."] },
  { title: "8. Klienti mladší ako 18 rokov", paragraphs: ["Klient mladší ako 18 rokov sa môže zúčastniť len s predchádzajúcim súhlasom rodiča alebo zákonného zástupcu. Táto osoba potvrdí súhlas e-mailom, uskutoční platbu a podporuje dodržiavanie týchto podmienok. Katey môže vyžiadať silnejší dôkaz alebo koučing odmietnuť, ak nemožno overiť vek, súhlas alebo bezpečnosť. Dostatočnosť súhlasu e-mailom zostáva predmetom právnej kontroly."] },
  { title: "9. Zdravie a bezpečnosť", items: ["Klienti musia úplne a pravdivo oznámiť zranenia, bolesť, ochorenia, tehotenstvo, lieky a všetky ďalšie okolnosti dôležité pre bezpečnú účasť.", "Po konzultácii klient písomne potvrdí zdravotné informácie a bezpečnostné poučenie.", "Pri zdravotných obavách je pred začatím alebo obnovením tréningu potrebný súhlas lekára.", "Klient musí dodržiavať pokyny, používať vhodné vybavenie a prostredie, rešpektovať svoje možnosti, pri bolesti, závrate alebo neobvyklých príznakoch okamžite prestať a vyhľadať zdravotnú pomoc."], paragraphs: ["Katey môže aktivitu pozastaviť, upraviť alebo odmietnuť, ak ju odôvodnene považuje za nebezpečnú. Klient zodpovedá za primerané zdravotné a úrazové poistenie."] },
  { title: "10. Nie je zdravotnou službou ani zárukou výsledku", paragraphs: ["Koučing, informácie o výžive a rozhovory založené na viere sú vzdelávacie a podporné služby. Nediagnostikujú, neliečia ani nevyliečia ochorenie a nenahrádzajú lekára, kvalifikovaného odborníka na výživu, psychoterapiu ani pohotovostnú pomoc. Nezaručujú konkrétny telesný, zdravotný, hmotnostný, finančný, emocionálny ani duchovný výsledok."] },
  { title: "11. Prevzatie rizika a zodpovednosť", paragraphs: ["Fyzická aktivita zahŕňa prirodzené riziká vrátane svalovej bolesti, natiahnutia, pádu a iného zranenia. Klient vedome prijíma bežné riziká, ktoré zostávajú napriek primeraným pokynom a starostlivosti.", "Katey naďalej zodpovedá za starostlivosť vyžadovanú právom. Zodpovednosť sa vylučuje alebo obmedzuje len v zákonom povolenom rozsahu. Nič nevylučuje zodpovednosť za úmyselné konanie, hrubú nedbanlivosť alebo zodpovednosť, ktorú zákon neumožňuje vylúčiť. Prijatie rizika neospravedlňuje nebezpečný alebo nedbanlivý koučing."] },
  { title: "12. Spolupráca a správanie klienta", paragraphs: ["Klient poskytuje informácie včas, zúčastňuje sa dohodnutých termínov, uskutočňuje platby a používa program len osobne. Obťažovanie, zneužívanie, nezákonné konanie alebo ohrozenie bezpečnosti môže viesť k pozastaveniu alebo ukončeniu. Finančné dôsledky sa posúdia primerane podľa okolností a povinného práva."] },
  { title: "13. Duševné vlastníctvo", paragraphs: ["Tréningové plány, videá, texty a ďalší obsah zostávajú vlastníctvom Katey alebo príslušného držiteľa práv. Klient dostáva osobné, neprenosné právo používať ich na účel programu. Bez písomného súhlasu ich nesmie zdieľať, predávať, zverejňovať, komerčne kopírovať ani používať na koučovanie iných."] },
  { title: "14. Osobné údaje a komunikácia", paragraphs: ["Osobné údaje sa spracúvajú podľa zásad ochrany osobných údajov. Písomné zdravotné údaje sa po skončení koučingu vymažú, ak ich uchovanie nevyžaduje povinný zákon. Stripe spracúva platobné údaje podľa vlastných podmienok. E-mail a WhatsApp možno používať na dohodnutú komunikáciu, nie však v núdzových situáciách. Cez nezabezpečené kanály by sa nemali posielať zbytočné citlivé údaje."] },
  { title: "15. Dovolenky a neprítomnosť Katey", paragraphs: ["Pri plánovanej dovolenke sú klienti vopred informovaní a program sa predĺži o počet dní neprítomnosti Katey. Pri neplánovanej dočasnej neprítomnosti sa program pozastaví a predĺži, keď bude môcť Katey pokračovať. Za dočasnú pauzu sa neposkytuje náhradný kouč ani vrátenie peňazí. Ak Katey trvalo nemôže poskytnúť zostávajúcu službu, povinné práva zostávajú nedotknuté."] },
  { title: "15. Dostupnosť a udalosti mimo kontroly", paragraphs: ["Katey môže termín presunúť pri chorobe, núdzovej situácii, technickom výpadku alebo inej udalosti mimo primeranej kontroly. Strany sa najprv pokúsia nájsť náhradný termín alebo predĺženie. Ak službu napokon nemožno poskytnúť, zákonné práva zostávajú zachované."] },
  { title: "16. Rozhodné právo a spory", paragraphs: ["V povolenom rozsahu sa uplatňuje švajčiarske právo bez jeho kolíznych noriem. Povinná ochrana spotrebiteľa a povinná miestna príslušnosť súdov zostávajú nedotknuté. Strany sa najprv pokúsia vyriešiť problém e-mailom. Ak sa neuplatňuje povinná príslušnosť, príslušné sú súdy pre Ettingen, Basel-Landschaft, Švajčiarsko."] },
  { title: "17. Kontakt a verzia", paragraphs: ["Otázky, zrušenia a právne oznámenia možno poslať na katey.coaching.newlife@gmail.com. Rozhodujúca je verzia prijatá pri platbe. Podstatné zmeny nemenia existujúci časovo obmedzený nákup spätne bez dohody."] },
];

export function TermsBody({ locale }: { locale: Locale }) {
  const sections = locale === "en" ? EN : locale === "de" ? DE : SK;
  return <>{sections.map((section) => <section key={section.title}><h2>{section.title}</h2>{section.paragraphs?.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.items && <ul>{section.items.map((item) => <li key={item}>{item}</li>)}</ul>}</section>)}</>;
}
