import type { Locale } from "@/i18n/routing";

type Section = { title: string; paragraphs?: string[]; items?: string[] };

const EN: Section[] = [
{title:"1. Provider and scope",paragraphs:["These Terms and Conditions apply to coaching services provided by Katarina Gröflin, trading as Katey Coaching, katey.coaching.newlife@gmail.com. Postal address: [FULL BUSINESS ADDRESS REQUIRED]. They apply to consumers and, where relevant, business clients. Mandatory rights under the law of a client's country of residence remain unaffected."]},
{title:"2. Contract formation",paragraphs:["The programme pages and payment options allow the client to select the service and billing plan. Before payment, Stripe Checkout displays the service, price and billing schedule and allows the order to be reviewed and corrected.","A contract is formed when the client accepts these Terms through the unticked checkout control and confirms the paid order. The version made available at checkout governs. Stripe displays the payment result and sends available confirmation electronically."]},
{title:"3. Services",items:["Full Transformation: personalised coaching for a fixed 90-day term, beginning when the client receives the first training video. It ends automatically and does not renew.","Move and Grow: monthly online training with weekly check-ins. It renews monthly until cancelled, has no minimum term and may be cancelled through the Stripe customer portal for the next billing cycle.","Nourish and Grow: monthly nutrition coaching with a first consultation of about 45 minutes, weekly check-ins, nutrition guidance and WhatsApp support. It renews monthly until cancelled and may be cancelled through the Stripe customer portal for the next billing cycle.","Find Your Way Through: a 60-minute one-to-one conversation paid in advance through Stripe at CHF 80 per session. It is faith-based coaching, not medical treatment, psychotherapy, crisis care or a substitute for healthcare."],paragraphs:["The description shown for the selected programme at checkout determines the agreed scope. Reasonable organisational or minor content changes may be made for safety, scheduling or adaptation, but the essential agreed service or value will not be materially reduced without the client's agreement where required by law."]},
{title:"4. Prices and payment",items:["Full Transformation: CHF 1,290 paid in full; two monthly payments of CHF 700 (CHF 1,400 total); or three monthly payments of CHF 480 (CHF 1,440 total).","Move and Grow: CHF 200 per monthly billing cycle.","Nourish and Grow: CHF 200 per monthly billing cycle.","Find Your Way Through: CHF 80 per 60-minute session, paid in advance."],paragraphs:["The total price and billing schedule are shown before payment. Payments are processed by Stripe. Instalments are a payment schedule for the agreed programme price, not separate monthly purchases. If a payment fails, coaching may pause until payment is completed, subject to mandatory law."]},
{title:"5. Appointments and client cancellations",paragraphs:["Appointments may be cancelled or rescheduled with at least 24 hours' notice. A later cancellation or missed appointment is forfeited without replacement or credit, subject to mandatory rights and any written exception confirmed by Katey. Coaching communication is not an emergency channel."]},
{title:"6. Cancellation, renewal and refunds",paragraphs:["Full Transformation ends after 90 days and does not renew. Early stopping or a change of mind does not itself create a refund entitlement, subject to mandatory law and section 14.","Move and Grow renews monthly until cancelled through the Stripe customer portal. Cancellation takes effect at the end of the current paid billing cycle and prevents the next renewal. Partial-period refunds are not normally provided, subject to mandatory law.","Nourish and Grow renews monthly until cancelled through the Stripe customer portal. Cancellation takes effect at the end of the current paid billing cycle and prevents the next renewal. Partial-period refunds are not normally provided, subject to mandatory law.","No exclusion of refunds or remedies applies where mandatory law requires them, where Katey cannot provide the agreed service, or where the service is defective."]},
{title:"7. EU/EEA withdrawal rights",paragraphs:["EU/EEA consumers generally have 14 days from conclusion of a distance service contract to withdraw. An unambiguous notice must be sent before the deadline to Katey Coaching, Katarina Gröflin, [FULL BUSINESS ADDRESS REQUIRED], katey.coaching.newlife@gmail.com. Katey will reimburse covered payments without undue delay and within 14 days of receiving the notice, using the original payment method unless otherwise agreed.","If the consumer expressly requests performance during the withdrawal period, a proportionate amount for services supplied before withdrawal may be due where permitted by law. The right expires after full performance only where all legal requirements, including prior express consent and acknowledgement, are met.","The separate early-performance consent is not pre-selected and is distinct from acceptance of these Terms and the Privacy Policy. Mandatory rights remain unaffected."]},
{title:"8. Clients under 18",paragraphs:["A client under 18 may participate only with prior, verifiable consent from a parent or legal guardian. The parent or guardian must contract, pay and support compliance. Katey may request proof or decline coaching where age, authority, consent or safety cannot be verified."]},
{title:"9. Health and safety",items:["Clients must provide complete and accurate information about injuries, pain, illness, pregnancy, medication and other matters relevant to safe participation.","Where a health concern exists, appropriate medical advice or approval is required before training begins or resumes.","Clients must follow instructions, use suitable equipment and surroundings, work within their abilities, stop for pain, dizziness or unusual symptoms, and seek medical help."],paragraphs:["Katey may pause, modify or refuse an activity she reasonably considers unsafe. The client remains responsible for appropriate health and accident insurance."]},
{title:"10. No medical service or guaranteed result",paragraphs:["Coaching, nutrition information and faith-based conversations are educational and supportive services. They do not diagnose, treat or cure disease and do not replace a doctor, registered dietitian, psychotherapist or emergency service. No specific result is guaranteed."]},
{title:"11. Assumption of risk and liability",paragraphs:["Physical activity involves ordinary risks, including soreness, strains, falls and other injury. The client accepts risks that remain despite reasonable instruction and care.","Katey remains responsible for the care required by applicable law. Liability is limited only to the extent legally permitted. Nothing excludes liability for intentional misconduct, gross negligence, injury to life, body or health, or any other liability that law does not allow to be excluded."]},
{title:"12. Client cooperation and conduct",paragraphs:["The client must provide information on time, attend appointments, complete payments and use programme materials personally. Harassment, abuse, unlawful conduct or a safety risk may lead to suspension or termination. Financial consequences will be assessed fairly and subject to mandatory law."]},
{title:"13. Personal data and communications",paragraphs:["Personal data is processed as described in the Privacy Notice. Email and WhatsApp may be used for agreed coaching communication where offered; they are not emergency channels. Stripe processes payment information under its own privacy documentation and may provide transaction status and billing details, but not necessarily full card details."]},
{title:"14. Katey's holidays and unavailability",paragraphs:["Planned holidays are communicated in advance and the programme is extended by affected days. If Katey is temporarily unable to provide the agreed service because of illness or another serious reason, affected sessions or the programme period may be postponed and extended. If the interruption lasts longer than 60 consecutive days, the client may terminate the remaining unused portion. Prepaid fees for services not provided are refunded proportionately, subject to mandatory law. This does not permit an indefinite pause or limit mandatory rights."]},
{title:"15. Governing law and disputes",paragraphs:["Swiss law applies to the extent permitted, excluding its conflict-of-law rules. Mandatory consumer protections and mandatory places of jurisdiction remain unaffected. Concerns should first be raised by email. Where no mandatory forum applies, the courts competent for Ettingen, Basel-Landschaft, Switzerland have jurisdiction."]},
{title:"16. Contact and version",paragraphs:["Questions, cancellations and legal notices may be sent to katey.coaching.newlife@gmail.com. Last updated: 6 October 2026. The version accepted at checkout governs. Material changes do not retroactively alter an existing fixed-term purchase without agreement."]},
{title:"17. Confidentiality",paragraphs:["Information shared during coaching is treated confidentially and is not disclosed without the client's consent, except where required by law, necessary for performance through authorised service providers, or legally permitted or required in connection with serious and immediate safety concerns. This does not prevent compliance with statutory obligations."]},
{title:"18. Reasonable changes and materials",paragraphs:["Katey may make reasonable organisational or minor content changes for delivery, safety or scheduling, but will not materially reduce the essential agreed service or value without agreement where required by law. Training plans, videos, written materials and similar content remain Katey's intellectual property. The client receives a personal, non-transferable licence for the programme purpose. Lawfully provided or downloaded materials may continue to be used privately after the programme ends, unless stated otherwise for a specific item. This does not grant continued access to an online portal, member area, course library or hosted content intended to expire. No ownership is transferred; resale, redistribution, sublicensing, publication, public-platform upload, sharing with third parties and commercial use are prohibited."]},
{title:"19. EU/EEA model withdrawal form",paragraphs:["To: Katey Coaching, Katarina Gröflin, [FULL BUSINESS ADDRESS REQUIRED], katey.coaching.newlife@gmail.com","I/We hereby withdraw from the contract for: [programme]. Ordered/booked on: [date]. Consumer name: [name]. Consumer address: [address]. Date: [date]. Signature (only if submitted on paper): [signature]."]},
];

const DE: Section[] = [
{title:"1. Anbieterin und Geltungsbereich",paragraphs:["Diese Allgemeinen Geschäftsbedingungen gelten für Coaching-Leistungen von Katarina Gröflin, handelnd unter Katey Coaching, katey.coaching.newlife@gmail.com. Postanschrift: [FULL BUSINESS ADDRESS REQUIRED]. Zwingende Rechte nach dem Recht des Wohnsitzstaates bleiben unberührt."]},
{title:"2. Vertragsschluss",paragraphs:["Vor der Zahlung zeigt Stripe Checkout Leistung, Preis und Zahlungsplan an und ermöglicht die Prüfung und Korrektur der Bestellung. Der Vertrag kommt zustande, wenn die nicht vorangekreuzte Zustimmung im Checkout abgegeben und die kostenpflichtige Bestellung bestätigt wird. Maßgeblich ist die beim Checkout bereitgestellte Fassung."]},
{title:"3. Leistungen",items:["Full Transformation: personalisiertes Coaching mit fester Laufzeit von 90 Tagen ab Erhalt des ersten Trainingsvideos; es endet automatisch und verlängert sich nicht.","Move and Grow: monatliches Online-Training mit wöchentlichen Check-ins; monatliche Verlängerung bis zur Kündigung, keine Mindestlaufzeit, Kündigung über das Stripe-Kundenportal zum nächsten Abrechnungszeitraum.","Nourish and Grow: monatliches Ernährungscoaching mit einer Erstberatung von etwa 45 Minuten, wöchentlichen Check-ins, Ernährungsbegleitung und WhatsApp-Unterstützung. Es verlängert sich monatlich bis zur Kündigung und kann über das Stripe-Kundenportal zum nächsten Abrechnungszeitraum gekündigt werden.","Find Your Way Through: 60-minütiges Einzelgespräch für CHF 80, vorab über Stripe bezahlt; glaubensbasiertes Coaching, keine medizinische Behandlung, Psychotherapie, Krisenhilfe oder Ersatz für Gesundheitsversorgung."],paragraphs:["Die beim Checkout angezeigte Beschreibung bestimmt den Umfang. Angemessene organisatorische oder geringfügige inhaltliche Änderungen sind möglich; die wesentliche Leistung oder ihr Wert wird ohne erforderliche Zustimmung nicht wesentlich reduziert."]},
{title:"4. Preise und Zahlung",items:["Full Transformation: CHF 1.290 vollständig; zwei Monatszahlungen zu CHF 700 (CHF 1.400 gesamt); oder drei zu CHF 480 (CHF 1.440 gesamt).","Move and Grow: CHF 200 je monatlichem Abrechnungszeitraum.","Nourish and Grow: CHF 200 je monatlichem Abrechnungszeitraum.","Find Your Way Through: CHF 80 je 60-minütigem Termin, im Voraus bezahlt."],paragraphs:["Preise und Zahlungsplan werden vor der Zahlung angezeigt. Zahlungen verarbeitet Stripe. Raten sind ein Zahlungsplan für den Programmpreis, keine einzelnen Monatskäufe. Bei fehlgeschlagener Zahlung kann das Coaching bis zur Zahlung pausieren, vorbehaltlich zwingenden Rechts."]},
{title:"5. Termine und Absagen",paragraphs:["Termine können mit mindestens 24 Stunden Vorlauf abgesagt oder verschoben werden. Bei späterer Absage oder Nichterscheinen verfällt der Termin ohne Ersatz oder Gutschrift, vorbehaltlich zwingender Rechte und schriftlich bestätigter Ausnahme. Coaching-Kommunikation ist kein Notfallkanal."]},
{title:"6. Kündigung, Verlängerung und Rückerstattung",paragraphs:["Full Transformation endet nach 90 Tagen ohne Verlängerung; vorzeitige Beendigung oder Meinungswechsel begründet allein keinen Erstattungsanspruch, vorbehaltlich zwingenden Rechts und §14. Move and Grow verlängert sich monatlich bis zur Kündigung über das Stripe-Kundenportal; die Kündigung wirkt zum Ende des bezahlten Zeitraums und verhindert die nächste Verlängerung. Eine anteilige Erstattung erfolgt normalerweise nicht. Nourish and Grow verlängert sich monatlich bis zur Kündigung über das Stripe-Kundenportal; die Kündigung wirkt zum Ende des bezahlten Zeitraums und verhindert die nächste Verlängerung. Eine anteilige Erstattung erfolgt normalerweise nicht. Gesetzlich erforderliche Erstattungen und Rechtsbehelfe bleiben unberührt."]},
{title:"7. Widerrufsrecht für EU-/EWR-Verbraucher",paragraphs:["EU-/EWR-Verbraucher haben bei Fernabsatz-Dienstleistungsverträgen grundsätzlich 14 Tage ab Vertragsschluss zum Widerruf. Der Widerruf ist an Katey Coaching, Katarina Gröflin, [FULL BUSINESS ADDRESS REQUIRED], katey.coaching.newlife@gmail.com zu senden. Erfasste Zahlungen werden spätestens innerhalb von 14 Tagen erstattet, grundsätzlich über dasselbe Zahlungsmittel.","Bei ausdrücklichem Verlangen nach Leistungsbeginn während der Widerrufsfrist kann ein gesetzlich zulässiger anteiliger Betrag für erbrachte Leistungen geschuldet sein. Das Recht erlischt nach vollständiger Leistung nur bei Erfüllung aller gesetzlichen Voraussetzungen. Die gesonderte Zustimmung zum vorzeitigen Beginn ist nicht vorangekreuzt und von AGB- und Datenschutzzustimmung getrennt."]},
{title:"8. Minderjährige",paragraphs:["Personen unter 18 Jahren dürfen nur mit vorheriger überprüfbarer Zustimmung der Eltern oder der gesetzlichen Vertretung teilnehmen. Diese muss den Vertrag schließen, zahlen und die Einhaltung unterstützen. Katey kann Nachweise verlangen oder Coaching ablehnen."]},
{title:"9. Gesundheit und Sicherheit",items:["Verletzungen, Schmerzen, Krankheiten, Schwangerschaft, Medikamente und andere relevante Umstände sind vollständig mitzuteilen.","Bei gesundheitlichen Bedenken ist geeigneter ärztlicher Rat oder eine Freigabe erforderlich.","Anweisungen und eigene Grenzen sind einzuhalten; bei ungewöhnlichen Symptomen ist sofort aufzuhören und medizinische Hilfe zu suchen."],paragraphs:["Katey kann unsichere Aktivitäten pausieren, anpassen oder ablehnen. Für Kranken- und Unfallversicherung bleibt die Kundin oder der Kunde verantwortlich."]},
{title:"10. Keine medizinische Leistung oder Erfolgsgarantie",paragraphs:["Coaching, Ernährungsinformationen und glaubensbasierte Gespräche sind Bildungs- und Unterstützungsleistungen. Sie ersetzen keine medizinische, psychotherapeutische oder Notfallversorgung und garantieren kein bestimmtes Ergebnis."]},
{title:"11. Risikoübernahme und Haftung",paragraphs:["Körperliche Aktivität birgt gewöhnliche Risiken. Katey haftet im gesetzlich erforderlichen Umfang. Haftung für Vorsatz, grobe Fahrlässigkeit, Schäden an Leben, Körper oder Gesundheit und andere gesetzlich nicht ausschließbare Fälle bleibt bestehen."]},
{title:"12. Mitwirkung und Verhalten",paragraphs:["Informationen sind rechtzeitig bereitzustellen, Termine wahrzunehmen, Zahlungen zu leisten und Programminhalte nur persönlich zu nutzen. Belästigung, Missbrauch, Rechtsverstöße oder Sicherheitsgefährdung können zur Beendigung führen."]},
{title:"13. Personendaten und Kommunikation",paragraphs:["Personendaten werden gemäß Datenschutzerklärung bearbeitet. E-Mail und WhatsApp können für vereinbarte Kommunikation genutzt werden, soweit angeboten; sie sind keine Notfallkanäle. Stripe verarbeitet Zahlungsdaten nach eigener Datenschutzerklärung."]},
{title:"14. Ferien und Abwesenheit von Katey",paragraphs:["Geplante Ferien werden angekündigt und verlängern das Programm um die betroffenen Tage. Bei vorübergehender Krankheit oder anderem wichtigen Grund können Termine oder der Zeitraum verschoben und verlängert werden. Dauert die Unterbrechung länger als 60 aufeinanderfolgende Tage, kann der nicht erbrachte Teil gekündigt und vorausbezahlte, nicht erbrachte Leistung anteilig erstattet werden. Eine unbefristete Pause ist nicht erlaubt; zwingende Rechte bleiben unberührt."]},
{title:"15. Anwendbares Recht und Streitigkeiten",paragraphs:["Soweit zulässig gilt Schweizer Recht. Zwingender Verbraucherschutz und zwingende Gerichtsstände bleiben unberührt. Anliegen sollen zunächst per E-Mail geklärt werden; ansonsten sind, soweit zulässig, die Gerichte für Ettingen, Basel-Landschaft zuständig."]},
{title:"16. Kontakt und Fassung",paragraphs:["Kontakt: katey.coaching.newlife@gmail.com. Letzte Aktualisierung: 6. Oktober 2026. Maßgeblich ist die beim Checkout akzeptierte Fassung. Bestehende Festzeitverträge werden durch spätere Änderungen nicht rückwirkend verändert."]},
{title:"17. Vertraulichkeit",paragraphs:["Im Coaching mitgeteilte Informationen werden vertraulich behandelt und nur mit Zustimmung offengelegt, außer bei gesetzlicher Pflicht, notwendiger Leistungserbringung durch autorisierte Dienstleister oder ernsthafter unmittelbarer Sicherheitsgefahr. Gesetzliche Pflichten bleiben unberührt."]},
{title:"18. Angemessene Änderungen und Materialien",paragraphs:["Angemessene organisatorische oder geringfügige inhaltliche Änderungen sind zulässig, ohne die wesentliche Leistung oder ihren Wert wesentlich zu reduzieren. Trainingspläne, Videos, Texte und ähnliche Inhalte bleiben geistiges Eigentum von Katey. Rechtmäßig erhaltene oder heruntergeladene Materialien dürfen privat weiter genutzt werden, gewähren aber keinen fortbestehenden Portal- oder Bibliothekszugang. Eigentum wird nicht übertragen; Verkauf, Weitergabe, Unterlizenzierung, Veröffentlichung, öffentliche Uploads und kommerzielle Nutzung sind verboten."]},
{title:"19. Muster-Widerrufsformular",paragraphs:["An: Katey Coaching, Katarina Gröflin, [FULL BUSINESS ADDRESS REQUIRED], katey.coaching.newlife@gmail.com","Hiermit widerrufe(n) ich/wir den Vertrag über: [Programm]. Gebucht am: [Datum]. Name: [Name]. Anschrift: [Anschrift]. Datum: [Datum]. Unterschrift (nur auf Papier): [Unterschrift]."]},
];

const SK: Section[] = [
{title:"1. Poskytovateľka a rozsah",paragraphs:["Tieto podmienky platia pre koučovacie služby Katariny Gröflin pod názvom Katey Coaching, katey.coaching.newlife@gmail.com. Poštová adresa: [FULL BUSINESS ADDRESS REQUIRED]. Povinné práva podľa krajiny bydliska klienta zostávajú nedotknuté."]},
{title:"2. Uzatvorenie zmluvy",paragraphs:["Pred zaplatením Stripe Checkout zobrazí službu, cenu a harmonogram platieb a umožní objednávku skontrolovať. Zmluva vzniká použitím vopred nezaškrtnutého potvrdenia v checkoute a potvrdením platenej objednávky. Rozhodujúce je znenie sprístupnené pri platbe."]},
{title:"3. Služby",items:["Full Transformation: personalizovaný koučovací program na 90 dní od prijatia prvého tréningového videa; skončí sa automaticky a neobnovuje sa.","Move and Grow: mesačné online tréningové predplatné s týždennými kontrolami; obnovuje sa do zrušenia, bez minimálnej doby, zrušenie cez zákaznícky portál Stripe pre ďalší cyklus.","Nourish and Grow: mesačný program výživového koučingu s prvou konzultáciou v trvaní približne 45 minút, týždennými kontrolami, podporou v oblasti výživy a podporou cez WhatsApp. Obnovuje sa mesačne do zrušenia a dá sa zrušiť cez zákaznícky portál Stripe pre ďalší cyklus.","Find Your Way Through: 60-minútový rozhovor za 80 CHF, zaplatený vopred cez Stripe; koučing založený na viere, nie zdravotná starostlivosť, psychoterapia ani krízová pomoc."],paragraphs:["Rozsah určuje opis pri platbe. Primerané organizačné alebo menšie obsahové zmeny sú možné; podstatná služba ani jej hodnota sa bez potrebného súhlasu podstatne nezníži."]},
{title:"4. Ceny a platba",items:["Full Transformation: 1 290 CHF vopred; dve platby po 700 CHF (spolu 1 400 CHF); alebo tri po 480 CHF (spolu 1 440 CHF).","Move and Grow: 200 CHF za mesačný cyklus.","Nourish and Grow: 200 CHF za mesačný cyklus.","Find Your Way Through: 80 CHF za 60-minútové stretnutie, vopred."],paragraphs:["Cena a harmonogram sa zobrazia pred platbou. Platby spracúva Stripe. Splátky sú kalendárom celej ceny, nie samostatnými nákupmi. Pri zlyhaní platby môže byť koučing pozastavený s výhradou povinného práva."]},
{title:"5. Termíny a zrušenia",paragraphs:["Termín možno zrušiť alebo presunúť najmenej 24 hodín vopred. Neskoré zrušenie alebo neúčasť znamená prepadnutie bez náhrady, s výhradou povinných práv a písomnej výnimky. Koučovacia komunikácia nie je núdzový kanál."]},
{title:"6. Zrušenie, obnovenie a vrátenie peňazí",paragraphs:["Full Transformation skončí po 90 dňoch bez obnovenia; skoré ukončenie samo osebe nezakladá nárok na vrátenie. Move and Grow sa obnovuje mesačne do zrušenia cez Stripe; zrušenie platí na konci zaplateného obdobia a zabráni ďalšiemu obnoveniu. Pomerné vrátenie sa bežne neposkytuje. Nourish and Grow sa obnovuje mesačne do zrušenia cez Stripe; zrušenie platí na konci zaplateného obdobia a zabráni ďalšiemu obnoveniu. Pomerné vrátenie sa bežne neposkytuje. Povinné nároky zostávajú zachované."]},
{title:"7. Právo spotrebiteľov EÚ/EHP na odstúpenie",paragraphs:["Spotrebiteľ má pri diaľkovej službe spravidla 14 dní od zmluvy na odstúpenie. Oznámenie treba poslať na Katey Coaching, Katarina Gröflin, [FULL BUSINESS ADDRESS REQUIRED], katey.coaching.newlife@gmail.com. Platby sa vrátia najneskôr do 14 dní, spravidla rovnakým spôsobom.","Pri výslovnej žiadosti o začatie počas lehoty môže byť splatná pomerná cena za poskytnutú službu. Zánik práva po úplnom poskytnutí je možný len pri splnení zákonných podmienok. Samostatný súhlas nie je vopred označený a je oddelený od súhlasu s podmienkami a zásadami ochrany údajov."]},
{title:"8. Klienti mladší ako 18 rokov",paragraphs:["Účasť je možná len s overiteľným súhlasom rodiča alebo zákonného zástupcu, ktorý uzatvorí zmluvu a zaplatí. Katey môže vyžiadať dôkaz alebo účasť odmietnuť."]},
{title:"9. Zdravie a bezpečnosť",items:["Klient musí oznámiť zranenia, bolesť, ochorenia, tehotenstvo, lieky a ďalšie relevantné okolnosti.","Pri zdravotných obavách je potrebná primeraná lekárska rada alebo súhlas.","Pokyny a vlastné hranice treba dodržiavať; pri neobvyklých príznakoch okamžite prestať a vyhľadať pomoc."],paragraphs:["Katey môže nebezpečnú aktivitu pozastaviť alebo odmietnuť. Klient zodpovedá za primerané poistenie."]},
{title:"10. Nie je zdravotnou službou ani zárukou výsledku",paragraphs:["Koučing, informácie o výžive a rozhovory založené na viere nenahrádzajú lekára, psychoterapiu ani pohotovosť a nezaručujú konkrétny výsledok."]},
{title:"11. Riziko a zodpovednosť",paragraphs:["Fyzická aktivita zahŕňa bežné riziká. Katey zodpovedá podľa práva; zodpovednosť za úmysel, hrubú nedbanlivosť, škodu na živote, tele alebo zdraví a iné nevylúčiteľné prípady zostáva zachovaná."]},
{title:"12. Spolupráca a správanie",paragraphs:["Klient poskytuje informácie včas, chodí na termíny, platí a obsah používa osobne. Obťažovanie, nezákonné konanie alebo ohrozenie bezpečnosti môže viesť k ukončeniu."]},
{title:"13. Osobné údaje a komunikácia",paragraphs:["Osobné údaje sa spracúvajú podľa zásad ochrany údajov. E-mail a WhatsApp možno používať na dohodnutú komunikáciu, ak sa ponúkajú; nie sú núdzové kanály. Stripe spracúva platobné údaje podľa svojich zásad."]},
{title:"14. Dovolenky a neprítomnosť Katey",paragraphs:["Plánované dovolenky sa oznámia a program sa predĺži o dotknuté dni. Pri dočasnej chorobe alebo inom vážnom dôvode možno termíny alebo obdobie presunúť a predĺžiť. Po viac ako 60 po sebe idúcich dňoch môže klient ukončiť neposkytnutú časť a dostať pomernú náhradu za vopred zaplatené neposkytnuté služby. Pauza nie je neobmedzená; povinné práva zostávajú zachované."]},
{title:"15. Rozhodné právo a spory",paragraphs:["V povolenom rozsahu platí švajčiarske právo. Povinná ochrana spotrebiteľa a miestna príslušnosť súdov zostávajú nedotknuté. Problémy sa najprv riešia e-mailom; inak sú príslušné súdy pre Ettingen, Basel-Landschaft, ak neplatí povinný iný súd."]},
{title:"16. Kontakt a verzia",paragraphs:["Kontakt: katey.coaching.newlife@gmail.com. Posledná aktualizácia: 6. októbra 2026. Rozhodujúca je verzia prijatá pri platbe; neskoršie zmeny nemenia existujúcu zmluvu spätne."]},
{title:"17. Dôvernosť",paragraphs:["Informácie z koučingu sa považujú za dôverné a neposkytujú sa bez súhlasu, okrem zákonnej povinnosti, autorizovaných poskytovateľov potrebných na službu alebo vážneho bezprostredného ohrozenia bezpečnosti. Zákonné povinnosti zostávajú zachované."]},
{title:"18. Primerané zmeny a materiály",paragraphs:["Primerané organizačné alebo menšie obsahové zmeny sú možné bez podstatného zníženia služby. Plány, videá, texty a podobný obsah zostávajú duševným vlastníctvom Katey. Zákonne získané alebo stiahnuté materiály možno po skončení programu používať súkromne, ale neposkytujú ďalší prístup k portálu alebo knižnici. Vlastníctvo sa neprevádza; predaj, šírenie, sublicencia, zverejnenie, verejné nahrávanie a komerčné použitie sú zakázané."]},
{title:"19. Vzorové odstúpenie",paragraphs:["Komu: Katey Coaching, Katarina Gröflin, [FULL BUSINESS ADDRESS REQUIRED], katey.coaching.newlife@gmail.com","Týmto odstupujem(e) od zmluvy na: [program]. Objednané dňa: [dátum]. Meno: [meno]. Adresa: [adresa]. Dátum: [dátum]. Podpis (iba na papieri): [podpis]."]},
];

export function TermsBody({ locale }: { locale: Locale }) {
  const sections = locale === "en" ? EN : locale === "de" ? DE : SK;
  return <>{sections.map((section, index) => { const title = section.title.replace(/^\d+\./, `${index + 1}.`); return <section id={index === 6 ? "withdrawal" : undefined} key={title}><h2>{title}</h2>{section.paragraphs?.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.items && <ul>{section.items.map((item) => <li key={item}>{item}</li>)}</ul>}</section>; })}</>;
}
