import Image from "next/image";
import { ArrowLeft, ArrowRight, Check } from "lucide-react";
import { getTranslations } from "next-intl/server";
import { Button } from "@/components/ui/button";
import { Link } from "@/i18n/navigation";
import type { Locale } from "@/i18n/routing";
import type { LocalizedProgram } from "@/lib/programs";

export async function ProgramDetail({ program, locale }: { program: LocalizedProgram; locale: Locale }) {
  const [t, nav] = await Promise.all([getTranslations({ locale, namespace: "programs" }), getTranslations({ locale, namespace: "nav" })]);
  return <article className="pb-16 md:pb-24"><div className="container-page section-pad-top-tight"><Link href="/programme" className="group inline-flex items-center gap-2 text-sm text-foreground/60 hover:text-[var(--plum)]"><ArrowLeft className="size-4" />{t("backToPrograms")}</Link><header className="mt-7 max-w-5xl"><p className="eyebrow">{t("realEyebrow")}</p><h1 className="mt-4 font-display text-[clamp(2.5rem,6vw,5rem)] leading-[1.01] text-[var(--plum)]">{program.title}</h1>{program.intro && <p className="mt-6 max-w-2xl text-lg leading-relaxed text-foreground/70">{program.intro}</p>}</header><div className="mt-10 grid items-start gap-8 md:grid-cols-12 md:gap-14"><div className="relative aspect-[4/3] overflow-hidden rounded-2xl md:col-span-5"><Image src={program.image} alt={program.imageAlt} fill priority sizes="(max-width: 768px) 100vw, 42vw" className="object-cover" /></div><section className="md:col-span-7"><h2 className="font-display text-3xl text-[var(--plum)]">{program.targetHeading}</h2><ul className="mt-6 space-y-4">{program.targetAudience.map((item) => <li key={item} className="flex items-start gap-3 text-foreground/74"><Check className="mt-1 size-4 shrink-0 text-[var(--clay)]" /><span className="leading-relaxed">{item}</span></li>)}</ul><p className="mt-7 font-display text-2xl italic text-foreground/88">{program.transition}</p></section></div><section className="mt-14 border-t border-foreground/10 pt-12 md:mt-20 md:grid md:grid-cols-12 md:gap-14"><h2 className="font-display text-3xl text-[var(--plum)] md:col-span-4">{program.includesHeading}</h2><div className="mt-7 md:col-span-8 md:mt-0"><ul className="divide-y divide-foreground/10 border-y border-foreground/10">{program.includes.map((item) => <li key={item} className="flex items-start gap-3 py-4 text-foreground/74"><Check className="mt-1 size-4 shrink-0 text-[var(--clay)]" /><span className="leading-relaxed">{item}</span></li>)}</ul><div className="mt-8 flex flex-col items-start gap-5 rounded-2xl bg-[var(--sand)] p-6 sm:flex-row sm:items-center sm:justify-between sm:p-8"><div><p className="eyebrow">{t("price")}</p><p className="mt-2 font-display text-3xl text-[var(--plum)]">{program.price} {program.currency} / {program.duration}</p></div><Button asChild size="lg" className="h-12 bg-[var(--plum)] px-7 text-white"><Link href={program.ctaHref || "/kontakt"}>{program.ctaLabel || nav("contact")}<ArrowRight className="ml-1 size-4" /></Link></Button></div></div></section></div></article>;
}
